### ISSUE TITLE
Deactivating the caching for objects and morphisms slow down the arithmatic in functor categories

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/FunctorCategories#11]
The "last" commit https://github.com/homalg-project/FunctorCategories/commit/851a97ed5581639f9bce5c2e5ae2199d724cc863 seems to slow down the performance:

Here is timing experiment:

In functor categories package, example `beilinson_quiver.g`, let
```
a := DirectSum( List( [ 1 .. 14 ], i -> Random( indec_projs ) ) );;
b := DirectSum( List( [ 1 .. 14 ], i -> Random( indec_projs ) ) );;
```
Before deactivating the caching:
```
B := Time( BasisOfExternalHom, [a,b] );;
#! 32.203597235 Secs.
Size(B);
#! 492
Time( Sum, [B] );
#! 5.403279159 Secs.
```
After deactivating the caching:
```
B := Time( BasisOfExternalHom, [a,b] );;
#! 32.473417945 Secs.
Size(B);
#! 492
Time( Sum, [B] );
#! 71.87341444499999 Secs.
```

**Comment by mohamed-barakat** [comment]
I will start debugging. Nevertheless, I find this weird because I did not deactivate the caches for natural transformations.

**Comment by kamalsaleh** [comment]
Thanks :), the time now drops to less than 4 Secs.
