### ISSUE TITLE
It would be nice to have a procedure that decides whether a given functor is (co)tilting object

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/FunctorCategories#12]
An  R-module M is tilting module if it has finite projective dimension, no higher self extensions and R as R-module can be co-resolved by objects in Additive closure of M.
See: http://www.math.uni-bonn.de/people/schroer/fd-modules-files/FD-TiltingModules.pdf

**Comment by mohamed-barakat** [comment]
What is the status of this?

**Comment by kamalsaleh** [comment]
I don't see why we might need this. I wouldn't mind closing it.
