### ISSUE TITLE
Allow to use CategoryOfRows as range of homomorphism structure

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/FunctorCategories#184]
Currently, `MatrixCategory` is hardcoded at many places in FunctorCategories. It would be nice if this could be changed to `CategoryOfRows` or made dynamic to support both. This would allow us to always use `CategoryOfRows` as the homomorphism structure in Algebroids (which in turn would allow us to remove `MatrixCategoryAsAdditiveClosureOfRingAsCategory` which is currently only used in Algebroids).

**Comment by mohamed-barakat** [comment]
I agree. When I am done with my restructuring I would be happy about a PR. If there is no further complications I can make the change myself.

**Comment by zickgraf** [comment]
I have given this a try:

The following method of `AsObjectInFunctorCategory` and the corresponding function in PreSheaves rely on the fact that `MatrixCategory` is an attribute and `FunctorCategory` has a cache: https://github.com/homalg-project/FunctorCategories/blob/4ef2d50740d3fb80e3c06d38c33a0d43d8219cd9/gap/FunctorCategories.gi#L263-L311

This is, for example, used here https://github.com/homalg-project/FunctorCategories/blob/4ef2d50740d3fb80e3c06d38c33a0d43d8219cd9/examples/doc/DifferentialModules.g#L134-L135 which has a side effect on https://github.com/homalg-project/FunctorCategories/blob/4ef2d50740d3fb80e3c06d38c33a0d43d8219cd9/examples/doc/DifferentialModules.g#L175

To avoid this, `AsObjectInFunctorCategory` must accept the functor category as the first argument instead and all callers have to be adapted. I won't try to do this because there are already so many version of `AsObjectInFunctorCategory`.

**Comment by mohamed-barakat** [comment]
Good, I will make the change.

**Comment by mohamed-barakat** [comment]
Is this gradually becoming obsolete?

**Comment by zickgraf** [comment]
The issue described in my above comment still exists. My PR only allows to use CategoryOfRows for the special case of the CategoryOfRows already being the homomorphism structure of an underlying Algebroid.
