### ISSUE TITLE
Bug with most recent CAP

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/FunctorCategories#4]
With CAP commit https://github.com/homalg-project/CAP_project/commit/be28fcb4ecd0845cd890e6a860e90f5ae3cc8504, `make test` fails with the following error:

```
# Running list 1 . . .
########> Diff in [ "./doc/_Chapter_Categories_of_functors.xml", 397,
  437 ]
# Input is:
EndU := InternalHomOnObjects( U, U ); # examples/doc/Hom.g:406
# Expected output:
<An object in The category of functors: Hopf algebra generated by
 the right quiver q(1)[t:1->1] -> Category of matrices over Q>
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMeth\
odFound
Error, no 1st choice method found for `InternalHomOnObjects' on 2 argu\
ments
```
(further errors omitted)

With CAP commit https://github.com/homalg-project/CAP_project/commit/e89f0d570eea05cc45a577795f4ce1ea03fca6da (one commit before the merge of https://github.com/homalg-project/CAP_project/pull/238 ) the tests succeed.

**Comment by sebasguts** [comment]
I will investigate this.

**Comment by sebasguts** [comment]
Should be fixed in https://github.com/homalg-project/CAP_project/pull/245

**Comment by zickgraf** [comment]
I confirm that this issue is fixed.
