### ISSUE TITLE
Bug with most recent QPA2

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/FunctorCategories#6]
https://github.com/oysteins/QPA2/commit/b33fbf31c3a96a29945ae8c31ffe527eae5ce0ba breaks the tests because `IsVertex` is removed. See https://circleci.com/gh/homalg-project/FunctorCategories/35

**Comment by mohamed-barakat** [comment]
On my laptop everything works.

**Comment by zickgraf** [comment]
I can reproduce the issue occurring in the CI with QPA2 at commit 3fde791f8e59ecda2009175fb398466c232fa371 and FunctorCategories at commit 7226ce0a510e7b10dff066cd75570f757ba54bb0.

Can you determine which package is declaring `IsVertex` on your laptop?

**Comment by zickgraf** [comment]
This is actually an issue in `Bialgebroids`. I have opened https://github.com/homalg-project/Bialgebroids/issues/28.
