### ISSUE TITLE
Lift/Colift are automatically installed for functors

### ISSUE THREAD

**Issue by sebastianpos** [homalg-project/FunctorCategories#6]
`Lift` and `Colift` are automatically installed for functor categories
even though that is mathematically wrong.

I suggest to use an explicit opt-in list for all basic operations
that can be reasonably lifted from the base category to the functor category.

**Comment by mohamed-barakat** [comment]
I agree that an opt-in list is the safe solution. I will wait and see how you do this in `AttributeCategoryForCAP`.

**Comment by mohamed-barakat** [comment]
Sorry, issues on homalg-project/FunctorCategories were disabled. I allowed them there. Could you please resubmit the issue there and I will add my comment afterwards.

**Comment by mohamed-barakat** [comment]
For me as a reminder, see

https://github.com/homalg-project/CAP_project/issues/96#issuecomment-422367880
